server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# openfeign 超时时间设置
ribbon:
  # 指建立连接所用时间，使用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指建立连接后从服务器读取可用资源所用的时间
  ConnectTimeout: 5000

# 使用root级别和package级别来控制日志的输入级别
logging:
  level:
    com.huawei.springcloud.service.PaymentService: debug