server:
  port: 8006

spring:
  application:
    name: cloud-consul-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health