server:
  port: 8000

spring:
  application:
    name: cloud-consul-order
  cloud:
    consul:
      # consul 注册地址
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
