server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      instance:
        instance-id: gateway-9527.com
        prefer-ip-address: true
info:
  app.name: xixi-microcloud
  company.name: www.xixi.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 1.0-SNAPSHOT

#    before http://myzuul.com:9527/microservicecloud-dept/dept/get/2
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**                   # 添加映射
  ignored-services:  "*"   # 屏蔽原服务名称的访问，单个指定具体，多个使用"*"
  prefix: /xixi            # 添加访问服务的路由前缀
#    after http://myzuul.com:9527/mydept/dept/get/1
