server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Lzx@123456

# 对mybatis的支持
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.huawei.springcloud.entities

eureka:
  client:
    # 允许注册到eureka服务注册中心
    register-with-eureka: true
    # 允许从注册服务中心抓取服务列表
    fetch-registry: true
    # 服务列表地址
    service-url:
      # 单机区域
      defaultZone: http://localhost:7001/eureka/
      # 集群区域
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002
  instance:
    instance-id: payment7001
    # 显示服务对应的IP地址
    prefer-ip-address: true
  server:
    # 关闭eureka自我保护机制
    enable-self-preservation: false
    # 清理无效节点时间间隔，单位毫秒（默认60秒）
    eviction-interval-timer-in-ms: 2000
