server:
  port: 1025 # linux 非root用户不能使用1024端口之内
#  追加订阅eureka服务注册地址
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/