server:
  port: 7001

eureka:
  instance:
    # eureka服务实例名称
#    hostname: localhost
    hostname: eureka7001.com
#    # eureka客户端向服务端发送心跳的时间间隔，单位是秒(默认30秒)
    lease-renewal-interval-in-seconds: 1
#    # eureka服务端在收到最后一次心跳后等待时间上限，单位是秒（默认是90秒），超时剔除服务
    lease-expiration-duration-in-seconds: 2
  server:
    # 禁用自我保护机制，保证服务被及时删除
    enable-self-preservation: false
    # 清理无效节点时间间隔，单位毫秒（默认60秒）
    eviction-interval-timer-in-ms: 2000
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # fasle 表示自己端就是注册中心，不需要抓取注册中心服务
    fetch-registry: false
    # eureka 服务注册地址列表，可以使用逗号","分隔多个列表地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/

